[package]
name = "blurz"
version = "0.5.0"
description = "Bluetooth lib for Rust using blueZ/dbus"
readme = "README.md"
authors = ["Attila Dusnoki <adusnoki@inf.u-szeged.hu>", "Ben Stern <bstern@fortian.com>"]
repository = "https://github.com/fortian/blurz"
keywords = ["bluetooth", "bluez", "ble"]
license = "BSD-2-Clause"
edition = "2018"

[lib]
name = "blurz"
path = "src/lib.rs"

[dependencies]
dbus = "0.9.0"
hex = "0.4"
